######################################################################
#
# File name : tb_pl_top_elaborate.do
# Created on: Thu Sep 10 16:36:32 +07 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -L xbip_utils_v3_0_9 -L c_reg_fd_v12_0_5 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_5 -L xbip_dsp48_addsub_v3_0_5 -L xbip_addsub_v3_0_5 -L c_addsub_v12_0_12 -L c_gate_bit_v12_0_5 -L xbip_counter_v3_0_5 -L c_counter_binary_v12_0_12 -L work -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work work work.tb_pl_top work.glbl -o tb_pl_top_opt
