######################################################################
#
# File name : tb_pl_top_compile.do
# Created on: Tue Sep 15 19:40:07 +07 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/work
vlib questa_lib/msim/xpm
vlib questa_lib/msim/xbip_utils_v3_0_9
vlib questa_lib/msim/c_reg_fd_v12_0_5
vlib questa_lib/msim/xbip_dsp48_wrapper_v3_0_4
vlib questa_lib/msim/xbip_pipe_v3_0_5
vlib questa_lib/msim/xbip_dsp48_addsub_v3_0_5
vlib questa_lib/msim/xbip_addsub_v3_0_5
vlib questa_lib/msim/c_addsub_v12_0_12
vlib questa_lib/msim/c_gate_bit_v12_0_5
vlib questa_lib/msim/xbip_counter_v3_0_5
vlib questa_lib/msim/c_counter_binary_v12_0_12
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_protocol_checker_v2_0_3
vlib questa_lib/msim/axi_vip_v1_1_3
vlib questa_lib/msim/processing_system7_vip_v1_0_5
vlib questa_lib/msim/lib_cdc_v1_0_2
vlib questa_lib/msim/proc_sys_reset_v5_0_12

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap work questa_lib/msim/work
vmap xpm questa_lib/msim/xpm
vmap xbip_utils_v3_0_9 questa_lib/msim/xbip_utils_v3_0_9
vmap c_reg_fd_v12_0_5 questa_lib/msim/c_reg_fd_v12_0_5
vmap xbip_dsp48_wrapper_v3_0_4 questa_lib/msim/xbip_dsp48_wrapper_v3_0_4
vmap xbip_pipe_v3_0_5 questa_lib/msim/xbip_pipe_v3_0_5
vmap xbip_dsp48_addsub_v3_0_5 questa_lib/msim/xbip_dsp48_addsub_v3_0_5
vmap xbip_addsub_v3_0_5 questa_lib/msim/xbip_addsub_v3_0_5
vmap c_addsub_v12_0_12 questa_lib/msim/c_addsub_v12_0_12
vmap c_gate_bit_v12_0_5 questa_lib/msim/c_gate_bit_v12_0_5
vmap xbip_counter_v3_0_5 questa_lib/msim/xbip_counter_v3_0_5
vmap c_counter_binary_v12_0_12 questa_lib/msim/c_counter_binary_v12_0_12
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_3 questa_lib/msim/axi_protocol_checker_v2_0_3
vmap axi_vip_v1_1_3 questa_lib/msim/axi_vip_v1_1_3
vmap processing_system7_vip_v1_0_5 questa_lib/msim/processing_system7_vip_v1_0_5
vmap lib_cdc_v1_0_2 questa_lib/msim/lib_cdc_v1_0_2
vmap proc_sys_reset_v5_0_12 questa_lib/msim/proc_sys_reset_v5_0_12

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work xilinx_vip  "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work work  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"/opt/cad/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"/opt/cad/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -64 -93 -work xpm  \
"/opt/cad/Xilinx/Vivado/2018.2/data/ip/xpm/xpm_VCOMP.vhd" \

vcom -64 -93 -work xbip_utils_v3_0_9  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work c_reg_fd_v12_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_4  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_pipe_v3_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_dsp48_addsub_v3_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_addsub_v3_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work c_addsub_v12_0_12  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/c_addsub_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work c_gate_bit_v12_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/c_gate_bit_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work xbip_counter_v3_0_5  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/xbip_counter_v3_0_vh_rfs.vhd" \

vcom -64 -93 -work c_counter_binary_v12_0_12  \
"../../../../v1.5_Deser.ip_user_files/ipstatic/hdl/c_counter_binary_v12_0_vh_rfs.vhd" \

vcom -64 -93 -work work  \
"../../../../v1.5_Deser.ip_user_files/ip/c_counter_binary_ch/sim/c_counter_binary_ch.vhd" \

vlog -64 -incr -work axi_infrastructure_v1_1_0  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work smartconnect_v1_0  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work axi_protocol_checker_v2_0_3  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/03a9/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work axi_vip_v1_1_3  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/b9a8/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -64 -incr -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L xilinx_vip -work processing_system7_vip_v1_0_5  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -64 -incr -work work  "+incdir+../../../../v1.5_Deser.srcs/sources_1/ip/pll" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ec67/hdl" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/5bb9/hdl/verilog" "+incdir+../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/70fd/hdl" "+incdir+/opt/cad/Xilinx/Vivado/2018.2/data/xilinx_vip/include" \
"../../../../v1.5_Deser.ip_user_files/bd/ps_topp/ip/ps_topp_processing_system7_0_0/sim/ps_topp_processing_system7_0_0.v" \
"../../../../v1.5_Deser.ip_user_files/ip/pll/pll_clk_wiz.v" \
"../../../../v1.5_Deser.ip_user_files/ip/pll/pll.v" \

vcom -64 -93 -work lib_cdc_v1_0_2  \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -64 -93 -work proc_sys_reset_v5_0_12  \
"../../../../v1.5_Deser.srcs/sources_1/bd/ps_topp/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -64 -93 -work work  \
"../../../../v1.5_Deser.ip_user_files/bd/ps_topp/ip/ps_topp_proc_sys_reset_0_1/sim/ps_topp_proc_sys_reset_0_1.vhd" \
"../../../../v1.5_Deser.ip_user_files/bd/ps_topp/sim/ps_topp.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/reg_map.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/reg_file.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/AdcClock.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/AdcData.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/DoubleNibbleDetect.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/Fdcr.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/GenPulse.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/sources_1/import/main/AdcFrame.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/Memory.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/adc_deser.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/new_types.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/bound_comparator.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/buffers_block.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/infrastructure_top.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/trigg_system.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/new/shaper_controller.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/new/pl_top.vhd" \
"../../../../v1.5_Deser.srcs/sources_1/imports/hdl/crystand_top.vhd" \
"../../../../v1.5_Deser.srcs/sim_1/imports/new/tb_adc.vhd" \
"../../../../v1.5_Deser.srcs/sim_1/new/tb_pl_top.vhd" \

# compile glbl module
vlog -work work "glbl.v"

