# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# IP: ip/pll/pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet

# Block Designs: bd/ps_topp/ps_topp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_topp || ORIG_REF_NAME==ps_topp} -quiet] -quiet

# IP: bd/ps_topp/ip/ps_topp_processing_system7_0_0/ps_topp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_topp_processing_system7_0_0 || ORIG_REF_NAME==ps_topp_processing_system7_0_0} -quiet] -quiet

# IP: bd/ps_topp/ip/ps_topp_proc_sys_reset_0_1/ps_topp_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps_topp_proc_sys_reset_0_1 || ORIG_REF_NAME==ps_topp_proc_sys_reset_0_1} -quiet] -quiet

# XDC: ip/pll/pll_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll/pll.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: ip/pll/pll_ooc.xdc

# XDC: bd/ps_topp/ps_topp_ooc.xdc
