//--------------------------------------------------------------
// This file is automatically generated. Do not edit this file
//--------------------------------------------------------------
`ifndef CFG_PARAMS_GENERATED_SVH
`define CFG_PARAMS_GENERATED_SVH

//--- automatically define section

// synopsys translate_off
`define SIMULATOR
// synopsys translate_on

`define CFG_NAME_NEXYS_A7

//--- user defined section

`define CLK_FREQ                    100000000
`define CLK_PERIOD                     10.0ns
`define CLK_HALF_PERIOD                 5.0ns
`define SYS_CLK                           200
`define LED_NUM                            16
`define RGB_NUM                             2
`define SEG7_NUM                            8

`endif //CFG_PARAMS_GENERATED_SVH
