# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/ip/c_counter_binary_ch/c_counter_binary_ch.xci
# IP: The module: 'c_counter_binary_ch' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/ip/c_counter_binary_ch/c_counter_binary_ch_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_ch'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/ip/c_counter_binary_ch/c_counter_binary_ch.xci
# IP: The module: 'c_counter_binary_ch' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/ip/c_counter_binary_ch/c_counter_binary_ch_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_ch'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
