######################################################################
#
# File name : tb_pl_top_wave.do
# Created on: Thu Sep 03 15:58:34 +07 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
