######################################################################
#
# File name : tb_pl_top_wave.do
# Created on: Tue Jul 30 11:20:23 +07 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
