######################################################################
#
# File name : tb_pl_top_simulate.do
# Created on: Tue Jul 30 11:20:23 +07 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -pli "/eda/xilinx/Vivado/2016.4/lib/lnx64.o/libxil_vsim.so" -lib work tb_pl_top_opt

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_pl_top_wave.do}

view wave
view structure
view signals

do {tb_pl_top.udo}

run 1000ns
