######################################################################
#
# File name : tb_pl_top_elaborate.do
# Created on: Tue Jul 30 11:20:20 +07 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/eda/mentor/2014-15/RHELx86/QUESTA-SV-AFV_10.4/questasim/bin/vopt -64 +acc=npr -L work -L xpm -L blk_mem_gen_v8_3_5 -L xbip_utils_v3_0_7 -L c_reg_fd_v12_0_3 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_3 -L xbip_dsp48_addsub_v3_0_3 -L xbip_addsub_v3_0_3 -L c_addsub_v12_0_10 -L c_gate_bit_v12_0_3 -L xbip_counter_v3_0_3 -L c_counter_binary_v12_0_10 -L unisims_ver -L unimacro_ver -L secureip -work work work.tb_pl_top work.glbl -o tb_pl_top_opt
