######################################################################
#
# File name : tb_pl_top_elaborate.do
# Created on: Thu Nov 19 22:34:46 +07 2020
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vopt -64 +acc=npr -L xbip_utils_v3_0_9 -L c_reg_fd_v12_0_5 -L xbip_dsp48_wrapper_v3_0_4 -L xbip_pipe_v3_0_5 -L xbip_dsp48_addsub_v3_0_5 -L xbip_addsub_v3_0_5 -L c_addsub_v12_0_12 -L c_gate_bit_v12_0_5 -L xbip_counter_v3_0_5 -L c_counter_binary_v12_0_12 -L work -L axi_infrastructure_v1_1_0 -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_3 -L axi_vip_v1_1_3 -L processing_system7_vip_v1_0_5 -L blk_mem_gen_v8_3_6 -L axi_bram_ctrl_v4_0_14 -L generic_baseblocks_v2_1_0 -L axi_register_slice_v2_1_17 -L fifo_generator_v13_2_2 -L axi_data_fifo_v2_1_16 -L axi_crossbar_v2_1_18 -L lib_cdc_v1_0_2 -L proc_sys_reset_v5_0_12 -L axi_protocol_converter_v2_1_17 -L axi_clock_converter_v2_1_16 -L blk_mem_gen_v8_4_1 -L axi_dwidth_converter_v2_1_17 -L xilinx_vip -L unisims_ver -L unimacro_ver -L secureip -L xpm -work work work.tb_pl_top work.glbl -o tb_pl_top_opt
