# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/bd/ps_topp/ip/ps_topp_processing_system7_0_0/ps_topp_processing_system7_0_0.xci
# IP: The module: 'ps_topp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/bd/ps_topp/ip/ps_topp_processing_system7_0_0/ps_topp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_topp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/bd/ps_topp/ip/ps_topp_processing_system7_0_0/ps_topp_processing_system7_0_0.xci
# IP: The module: 'ps_topp_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/aandreev/pro/v1.5_Deser/v1.5_Deser.srcs/sources_1/bd/ps_topp/ip/ps_topp_processing_system7_0_0/ps_topp_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps_topp_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
